apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homelab
resources:
  - serviceaccount.yaml
  - rbac.yaml
  - pvc.yaml
  - export-pvc.yaml
  - configmap.yaml
  - external-secret.yaml
  - deployment.yaml
