apiVersion: v1
kind: ConfigMap
metadata:
  name: vaultwarden-configmap
  namespace: homelab
data:
  DOMAIN: "https://pwd.wst.sh"
  WEBSOCKET_ENABLED: "true"
  SSO_ENABLED: "true"
  SSO_AUTHORITY: "https://id.wst.sh"