apiVersion: v1
kind: Service
metadata:
  name: tinyauth
  namespace: auth
  labels:
    app: tinyauth
spec:
  selector:
    app: tinyauth
  ports:
    - name: http
      port: 3000
      targetPort: 3000