apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:  
  - deployment.yaml
  - external-secret.yaml
  - ingress.yaml
  - service-account.yaml
  - service.yaml