apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: notification-secret
  namespace: flux-system
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: infisical-store
    kind: ClusterSecretStore
  target:
    name: notification-secret
  data:
    - secretKey: token
      remoteRef:
        key: /Telegram/BOT_TOKEN
    - secretKey: address
      remoteRef:
        key: /Telegram/USER_ID