apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./_namespaces/
  - ./pocket-id/
  - ./tinyauth/
  - ./grafana/
  - ./kite/
  - ./beszel-hub/
  - ./glance/
  - ./prometheus/
  - ./glance-k8s/
  - ./uptime-kuma/
  - ./kube-state-metrics/
  - ./portainer/
  - ./vaultwarden/
  - ./drizzle-gateway/
  - ./postgres/
  - ./redis/
  - ./n8n/
  - ./postgresus/