apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-configmap
  namespace: observability
data:
  grafana.ini: |
    [server]
    root_url = https://dash.wst.sh/
    
    [auth]
    oauth_allow_insecure_email_lookup = true
    disable_login_form = true