apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: infisical-store
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            key: clientId
            name: infisical-auth
            namespace: external-secrets
          clientSecret:
            key: clientSecret
            name: infisical-auth
            namespace: external-secrets
      secretsScope:
        # 如果使用 self-hosted infisical，需要配置 hostAPI
        # hostAPI: https://api.infisical.com/v1
        projectSlug: realtong-homelab
        environmentSlug: prod
